package report

import (
	"fmt"
	"strings"

	"nirvishaai/backend/scanner"
)

func GenerateMarkdown(result scanner.ScanResult) []byte {
	var sb strings.Builder

	sb.WriteString("# NirvishaAI Security Report\n\n")
	sb.WriteString(fmt.Sprintf("**Domain:** `%s`  \n", result.Domain))
	sb.WriteString(fmt.Sprintf("**Scanned:** %s  \n", formatDate(result.ScannedAt)))
	sb.WriteString(fmt.Sprintf("**Security Score:** %d / 100\n\n", result.Score))

	critical, high, medium, low := countBySeverity(result.Checks)
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|---|---|\n")
	sb.WriteString(fmt.Sprintf("| 🔴 Critical | %d |\n", critical))
	sb.WriteString(fmt.Sprintf("| 🟠 High | %d |\n", high))
	sb.WriteString(fmt.Sprintf("| 🟡 Medium | %d |\n", medium))
	sb.WriteString(fmt.Sprintf("| 🔵 Low | %d |\n\n", low))

	sb.WriteString("## Vulnerabilities\n\n")
	for _, check := range result.Checks {
		icon := "✅"
		if !check.Passed {
			icon = severityIcon(check.Severity)
		}
		sb.WriteString(fmt.Sprintf("### %s %s\n\n", icon, check.Title))
		sb.WriteString(fmt.Sprintf("**Severity:** %s  \n", strings.ToUpper(string(check.Severity))))
		sb.WriteString(fmt.Sprintf("**Status:** %s  \n\n", passedLabel(check.Passed)))
		sb.WriteString(fmt.Sprintf("%s\n\n", check.Description))

		if check.Evidence != "" {
			sb.WriteString("**Evidence:**\n```\n")
			sb.WriteString(check.Evidence)
			sb.WriteString("\n```\n\n")
		}

		if !check.Passed && check.FixHint != "" {
			sb.WriteString("**How to Fix:**\n```\n")
			sb.WriteString(check.FixHint)
			sb.WriteString("\n```\n\n")
		}
		sb.WriteString("---\n\n")
	}

	if len(result.AIAnalysis) > 0 {
		sb.WriteString("## AI Analysis (বাংলা)\n\n")
		for _, vuln := range result.AIAnalysis {
			sb.WriteString(fmt.Sprintf("### %s\n\n", vuln.CheckName))
			sb.WriteString(fmt.Sprintf("**ব্যাখ্যা:** %s\n\n", vuln.Explanation))
			sb.WriteString(fmt.Sprintf("**Risk Level:** %s\n\n", vuln.RiskLevel))
			if vuln.HowToExploit != "" {
				sb.WriteString(fmt.Sprintf("**কীভাবে Exploit হতো:** %s\n\n", vuln.HowToExploit))
			}
			if vuln.HowToFix != "" {
				sb.WriteString(fmt.Sprintf("**Fix:** %s\n\n", vuln.HowToFix))
			}
			if vuln.CodeSnippet != "" {
				sb.WriteString("```\n")
				sb.WriteString(vuln.CodeSnippet)
				sb.WriteString("\n```\n\n")
			}
			sb.WriteString("---\n\n")
		}
	}

	sb.WriteString("> Generated by [NirvishaAI](https://nirvishaai.com) — Non-intrusive security scan.\n")
	return []byte(sb.String())
}

func severityIcon(s scanner.Severity) string {
	switch s {
	case scanner.Critical:
		return "🔴"
	case scanner.High:
		return "🟠"
	case scanner.Medium:
		return "🟡"
	default:
		return "🔵"
	}
}

func passedLabel(passed bool) string {
	if passed {
		return "✅ Passed"
	}
	return "❌ Failed"
}
