package report

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"nirvishaai/backend/scanner"

	"github.com/jung-kurt/gofpdf"
)

func GeneratePDF(result scanner.ScanResult) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetMargins(20, 20, 20)

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetTextColor(220, 50, 50)
	pdf.Cell(0, 12, "NirvishaAI Security Report")
	pdf.Ln(14)

	// Domain & Date
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(80, 80, 80)
	pdf.Cell(0, 7, fmt.Sprintf("Domain: %s", result.Domain))
	pdf.Ln(7)
	pdf.Cell(0, 7, fmt.Sprintf("Scanned: %s", formatDate(result.ScannedAt)))
	pdf.Ln(12)

	// Score
	scoreColor := scoreToColor(result.Score)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(scoreColor[0], scoreColor[1], scoreColor[2])
	pdf.Cell(0, 10, fmt.Sprintf("Security Score: %d / 100", result.Score))
	pdf.Ln(14)

	// Summary counts
	critical, high, medium, low := countBySeverity(result.Checks)
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(0, 7, fmt.Sprintf("Critical: %d   High: %d   Medium: %d   Low: %d", critical, high, medium, low))
	pdf.Ln(12)

	// Divider
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(8)

	// Vulnerability Details
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(0, 10, "Vulnerability Details")
	pdf.Ln(12)

	for _, check := range result.Checks {
		if check.Passed {
			continue
		}
		sev := strings.ToUpper(string(check.Severity))
		sevColor := severityColor(check.Severity)

		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(sevColor[0], sevColor[1], sevColor[2])
		pdf.Cell(30, 8, fmt.Sprintf("[%s]", sev))
		pdf.SetTextColor(0, 0, 0)
		pdf.MultiCell(0, 8, check.Title, "", "", false)
		pdf.Ln(2)

		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(60, 60, 60)
		pdf.MultiCell(0, 6, check.Description, "", "", false)
		pdf.Ln(2)

		if check.Evidence != "" {
			pdf.SetFont("Courier", "", 9)
			pdf.SetFillColor(245, 245, 245)
			pdf.MultiCell(0, 6, "Evidence: "+check.Evidence, "", "", true)
			pdf.Ln(2)
		}

		if check.FixHint != "" {
			pdf.SetFont("Helvetica", "I", 10)
			pdf.SetTextColor(30, 120, 30)
			pdf.MultiCell(0, 6, "Fix: "+check.FixHint, "", "", false)
		}
		pdf.Ln(6)
	}

	// AI Analysis
	if len(result.AIAnalysis) > 0 {
		pdf.AddPage()
		pdf.SetFont("Helvetica", "B", 14)
		pdf.SetTextColor(0, 0, 0)
		pdf.Cell(0, 10, "AI Analysis (Bengali)")
		pdf.Ln(12)

		for _, vuln := range result.AIAnalysis {
			pdf.SetFont("Helvetica", "B", 11)
			pdf.SetTextColor(50, 50, 150)
			pdf.MultiCell(0, 8, vuln.CheckName, "", "", false)

			pdf.SetFont("Helvetica", "", 10)
			pdf.SetTextColor(0, 0, 0)
			pdf.MultiCell(0, 6, vuln.Explanation, "", "", false)
			pdf.Ln(4)

			if vuln.HowToFix != "" {
				pdf.SetFont("Helvetica", "I", 10)
				pdf.SetTextColor(30, 120, 30)
				pdf.MultiCell(0, 6, "Fix: "+vuln.HowToFix, "", "", false)
			}
			pdf.Ln(8)
		}
	}

	// Footer
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(150, 150, 150)
	pdf.SetY(-15)
	pdf.Cell(0, 10, "Generated by NirvishaAI (https://nirvisha.rexio.pro) — Powered by RexiO (https://rexio.pro)")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func scoreToColor(score int) [3]int {
	if score >= 80 {
		return [3]int{30, 150, 30}
	}
	if score >= 50 {
		return [3]int{200, 130, 0}
	}
	return [3]int{200, 30, 30}
}

func severityColor(s scanner.Severity) [3]int {
	switch s {
	case scanner.Critical:
		return [3]int{180, 0, 0}
	case scanner.High:
		return [3]int{200, 80, 0}
	case scanner.Medium:
		return [3]int{180, 140, 0}
	default:
		return [3]int{80, 80, 200}
	}
}

func countBySeverity(checks []scanner.CheckResult) (critical, high, medium, low int) {
	for _, c := range checks {
		if c.Passed {
			continue
		}
		switch c.Severity {
		case scanner.Critical:
			critical++
		case scanner.High:
			high++
		case scanner.Medium:
			medium++
		case scanner.Low:
			low++
		}
	}
	return
}

func formatDate(s string) string {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return s
	}
	return t.Format("02 Jan 2006, 15:04 UTC")
}
